### ISSUE TITLE
Simply internal logging API

### ISSUE THREAD

**Issue by msekletar** [rh-lab-q/server-side-dependency-solving#102]
Current API which ssds components use for logging is ```ssds_log()``` function. I think that prefixing ```ssds_```  is unnecessary, because function is not a part of any public API. Hence, name-spacing is rather harmful than useful in this case. It requires more typing and makes code less readable.

I think, it would be better to introduce top-level logging function for each priority level, e.g. ```log_error(), log_warn(), log_debug()```. 

This suggestion also applies to other internal APIs through out the code base. Each function which is not public should  not have prefixed name.

**Comment by mruprich** [comment]
The ssds prefix has already been removed. As for the logging part, the whole project is being modified to use syslog for logging..

**Comment by msekletar** [comment]
In https://github.com/rh-lab-q/server-side-dependency-solving/blob/master/src/server/server.c I still see a lot of uses of ```ssds_log``` API.

**Comment by jozkar** [comment]
we're developing in different branch. (branch log in this case)

**Comment by msekletar** [comment]
Ahh, then disregard my comment.
