### ISSUE TITLE
Create a class for libsolve and hawkey.

### ISSUE THREAD

**Issue by phracek** [rh-lab-q/server-side-dependency-solving#17]
The class should be able to receive a data from either XML file.
class should be able to communicate with libsolve and hawkey library to resolve dependencie.
Input to class should be:
- package to install (like GIMP)
- architecture type (i686 or x86_64)
- OS version (line Fedora 20)

Later on it can be enhanced.

**Comment by mruprich** [comment]
adea15e1647144a87d68968894010264fde82a60
