### ISSUE TITLE
Sending @System.solv from client and saving at server side

### ISSUE THREAD

**Issue by mruprich** [rh-lab-q/server-side-dependency-solving#29]
Find a way how to send @System.solv from client to server...

**Comment by wscherfel** [comment]
Client now sends @System.solv file everytime he starts, the file is saved in the build folder where is binary file.

**Comment by jozkar** [comment]
Transferred @System.solv file on server side has same size as original @System.solv file, but its content is corrupted!

**Comment by wscherfel** [comment]
File seems ok on my computer, I verified by using hexdumping the original and the saved file and using diff on results and it did not show any difference.

**Comment by jozkar** [comment]
I probably found error on my side, so i am sorry for fake alert. I found, then when i run it for first time, than @System.solv is ok, but when i overwrite it by running ssds-client again, than is @System.solv corrupted. (maybe this problem is just at my virual machine, so its ok)
