### ISSUE TITLE
Package will be installed by rpm itself

### ISSUE THREAD

**Issue by phracek** [rh-lab-q/server-side-dependency-solving#41]
All packages installed by ssds are going to be used rpm library directly.

**Comment by phracek** [comment]
It is may be off topic but what about to write a client in Python?
Does it make sense?
Server should be in C code.

What do you think about it?

**Comment by jozkar** [comment]
we can rewrite it in future if it will be faster than in c

**Comment by jozkar** [comment]
in 0.2.0 are packages just installed by calling system command. in 0.3.0 will be installed, updated and erased by rpmlib functions (viz. #62 )
