### ISSUE TITLE
Project is not possible to compile

### ISSUE THREAD

**Issue by phracek** [rh-lab-q/server-side-dependency-solving#50]
The project is not possible to compile. Cmake show errors.
Run command cmake ../ from build directory

$ cmake ../
-- The C compiler identification is GNU 5.1.1
-- The CXX compiler identification is GNU 5.1.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.44.1
-- checking for module 'json-glib-1.0'
--   found json-glib-1.0, version 1.0.4
-- checking for module 'hawkey'
--   found hawkey, version 0.5.7
-- checking for module 'librepo'
--   found librepo, version 1.7.16
-- checking for module 'check'
--   package 'check' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  cmake/Modules/FindCheck.cmake:4 (PKG_CHECK_MODULES)
  CMakeLists.txt:58 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/phracek/work/programming/server-side-dependency-solving/CMakeFiles/CMakeOutput.log".

**Comment by mruprich** [comment]
48c146d88d7b4e305653bf1f891288cf90290820
