### ISSUE TITLE
Sigsegv on server side in function ssds_dep_query

### ISSUE THREAD

**Issue by wscherfel** [rh-lab-q/server-side-dependency-solving#57]
Server crashes in ssds_dep_query function during solving dependencies. 

This bug showed after data and comm socket were separated and @System.solv file sending was finished although I dont see how that could have caused it.

**Comment by jozkar** [comment]
server crashes only, if is runned via valgrind (and solving takes almost 10-15 minutes!!!) i suggest to do not running server via valgrind, if it will not be needed

This issue is probably solved. Please reopen it, if the issue throw again.
