### ISSUE TITLE
Critical errors in JSON under valgrind on server side.

### ISSUE THREAD

**Issue by wscherfel** [rh-lab-q/server-side-dependency-solving#58]
Client sends a message with code 10 and no other contents, server parses it if its not run under valgrind but if it is it writes several Json-CRITICAL errors. Is there some other needed information other than mentioned code 10?

**Comment by phracek** [comment]
Please attach also log from valgrind.
It is helpful for analyse.

Could we have documented JSON strukture and protokol?
Example is good for next steps.

**Comment by phracek** [comment]
First part is for Walter and second part is for Michal

**Comment by jozkar** [comment]
JSON structure and protocol is documented in protocol.txt

critical errors in JSON under valgrind on server side are not presented now (probably was solved by some minor change in some of src/common/* files.)

Please reopen this issue, if it will be actual, but for now it is not.
