### ISSUE TITLE
Client connects remote server

### ISSUE THREAD

**Issue by phracek** [rh-lab-q/server-side-dependency-solving#59]
We should define a way how to connect remote server from client.
Think about how we should define ports and IP address of remote server?
/etc/yum.repos.d/?

Also should it be a separate file like /etc/ssds.conf?

Look and Fedora /etc directory or eventually discuss it on #yum channel on freenode with YUM/DNF team.

**Comment by phracek** [comment]
I suggest to create a library in common directory so that as client as server is able read them.
Function should be used by both binaries.

**Comment by jozkar** [comment]
i have just another idea (if is it stupid so ignore it). What if we implement something like DHCP for SSDS, like first time will be some specific server asked for address and port of SSDS server and from the answer will be created config file (so config file will not be part of SSDS install package). what do you think about it?

**Comment by jozkar** [comment]
Already done. Previous idea is realized by Fedora infrastructure
