### ISSUE TITLE
Client reads configuration file and connects to specific ports client/server

### ISSUE THREAD

**Issue by phracek** [rh-lab-q/server-side-dependency-solving#61]
Client should be able to read default configuration and connects to relevant port.

Common functions should be provided by #59 issue.
Test suite is also welcome.

**Comment by SimonMatej** [comment]
Parsing is added into cfg_parsing_connection_info branch. But, because garbage collector is broken in that version of project (calling ssds_malloc throws segfault), client currently crashes.
