### ISSUE TITLE
Server ends in a weird way

### ISSUE THREAD

**Issue by mruprich** [rh-lab-q/server-side-dependency-solving#78]
If I understand the code correctly, the server accepts one connection and if it somehow fails the server will terminate. I don't see a reason why... I think that it should log some info into log file but than it should restore the socket and keep listening. If the server runs as a daemon and it ends with the first bad socket operation thats not very useful I guess...

**Comment by jozkar** [comment]
server now end only by calling signal interuption, in other error caases just print error message into log and close old socket
