### ISSUE TITLE
Showing message when @solv file should be send again

### ISSUE THREAD

**Issue by phracek** [rh-lab-q/server-side-dependency-solving#85]
I suggest to show message that @Solv file should be send again.

Example:
1) SSDS programs install / update / erase packages based on server requirments.
2) DNF install a program by themself
3) SSDS tries to install a new package. Now It should be shown message like:
DNF install packages by themself. We need to make initial steps again. If you don't want to use SSDS call ssds-client --disconnect.

**Comment by jozkar** [comment]
Done
