### ISSUE TITLE
Remove Garbage Collector

### ISSUE THREAD

**Issue by phracek** [rh-lab-q/server-side-dependency-solving#89]
Remove complete Garbage Collector.
Use gcc cleanup macros like here:
https://github.com/systemd/systemd/blob/master/src/basic/alloc-util.c
https://github.com/systemd/systemd/blob/master/src/basic/macro.h#L45

or t_alloc.

**Comment by phracek** [comment]
Several time there is mentioned malloc which does not check if it is correct.
Afterwords variables are used like x->b = 0
Instead of this we can use calloc.

Like here: https://github.com/rh-lab-q/server-side-dependency-solving/blob/master/src/common/params.c#L104

**Comment by mruprich** [comment]
f2a41f82c6fcb29a4e1d225e727e9e7156518fa9
