### ISSUE TITLE
mem_management.c uses an open-coded implementation of doubly-linked lists

### ISSUE THREAD

**Issue by kdudka** [rh-lab-q/server-side-dependency-solving#98]
Why does ```mem_management.c``` use an open-coded implementation of a doubly-linked list?

Would not it be better to use the list implementation provided by glib if you link the library anyway?

**Comment by mruprich** [comment]
The mem_management module will be removed soon anyway. We will not use it in the project anymore...

**Comment by mruprich** [comment]
f2a41f82c6fcb29a4e1d225e727e9e7156518fa9
